### ISSUE TITLE
No devices connected.

### ISSUE THREAD

**Issue by nprotecc** [basemprince/pogo-pvp-assistant#1]
Hello, after creating the image in Docker, I try to run the following command " docker run --net="host" -e DISPLAY=unix$DISPLAY pogo-bot ", but I only get a message saying that no ADB device is connected. How can I solve this issue?

2023-08-05 21:11:55 * daemon not running; starting now at tcp:5037
2023-08-05 21:11:55 * daemon started successfully
2023-08-05 21:12:05 Traceback (most recent call last):
2023-08-05 21:12:05   File "/app/utils.py", line 301, in connect_to_device
2023-08-05 21:12:05     client = scrcpy.Client(device=adb.device_list()[0])
2023-08-05 21:12:05 IndexError: list index out of range
2023-08-05 21:12:05 
2023-08-05 21:12:05 During handling of the above exception, another exception occurred:
2023-08-05 21:12:05 
2023-08-05 21:12:05 Traceback (most recent call last):
2023-08-05 21:12:05   File "/app/main.py", line 61, in <module>
2023-08-05 21:12:05     client = utils.connect_to_device("127.0.0.1:5037")
2023-08-05 21:12:05   File "/app/utils.py", line 303, in connect_to_device
2023-08-05 21:12:05     raise Exception("No devices connected.")
2023-08-05 21:12:05 Exception: No devices connected.

**Comment by basemprince** [comment]
Hi, sorry for the delayed response as I am not an expert with docker containers. I am assuming your host machine is running windows? If so, i created another branch with a different docker setup. I added the instructions to the readme at the bottom, so let me know how it goes.

**Comment by nprotecc** [comment]
I managed to get it working on an Ubuntu virtual machine. Thank you for the project!

**Comment by basemprince** [comment]
Great, how is it running there with the double nested virtualization? also did you have no luck with the pushed code on the Windows-Docker branch setup on Windows?
